### ISSUE TITLE
Accountbeheer screen todo left

### ISSUE THREAD

**Issue by noirscape** [ev1l0rd/fys-luggageM#32]
What's left on my controller/screen:

- [x] Sanity checks, sanity checks. These must be implemented for deactivating and resetting the password for a user to ensure that users dont accidentically reset their own password or deactivate themselves.
- [x] Reset password functionality isn't updated to the new schema yet.
- [x] Search bar should actually do something (and be moved down a couple pixels).
- [x] i18n new fields
